name: Plugin build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        game: [csgo, portal2]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout hl2sdk
      run: |
        git config -f .gitmodules submodule.hl2sdk.branch ${{ matrix.game }}
        git submodule update --remote
    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: version.h
        contents: |
          #define CVAR_UNHIDE_VERSION "${{ env.GITHUB_RUN_ID }}-${{ matrix.game }}"
        write-mode: overwrite
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild
    - name: Run MSBuild
      run: msbuild /m /p:Configuration=Release cvar-unhide.sln
    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
        name: addons-${{ matrix.game }}
        path: addons
        retention-days: 5
