name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
        game: [csgo, portal2]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout hl2sdk
      run: |
        git config -f .gitmodules submodule.hl2sdk.branch ${{ matrix.game }}
        git submodule sync
        git submodule update --init --remote
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD
    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: version.h
        contents: |
          #define CVAR_UNHIDE_VERSION "${{ steps.current-time.outputs.formattedTime }}.${{ github.run_number }}-${{ matrix.game }}"
        write-mode: overwrite
    - name: Add MSBuild to PATH
      if: ${{ matrix.os == 'windows-2019' }}
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build plugin (Windows)
      if: ${{ matrix.os == 'windows-2019' }}
      run: msbuild /m /p:Configuration=Release cvar-unhide.sln
    - name: Build plugin (Linux)
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      uses: i386/ubuntu:18.04
      with:
        args: make plugin
    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
        name: addons-${{ matrix.game }}-${{ matrix.os }}
        path: addons
        retention-days: 5
